# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dc946d5269db3621a187c4cc70528fe2d4a899f89c90cfddcfdadb9756db5649154dd514b75adf28849cbf947eed2d0ddcba1d715361ba4979da9ef7d00a047

test:
  secret_key_base: b4c015a047f67e0d7e67da03ab90077b045facf1bc118a62b66b88c1ab9e1296a5e55599500e1dbe06b233da5468111a8c4042a3741199b54096214bfb6ea07f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
